<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Type-Conversion" data-toc-modified-id="Type-Conversion-0.1"><span class="toc-item-num">0.1&nbsp;&nbsp;</span>Type Conversion</a></span></li><li><span><a href="#torch.Tensor-can-switch-to-and-from-the-np.ndarray" data-toc-modified-id="torch.Tensor-can-switch-to-and-from-the-np.ndarray-0.2"><span class="toc-item-num">0.2&nbsp;&nbsp;</span><code>torch.Tensor</code> can switch to and from the <code>np.ndarray</code></a></span></li></ul></li><li><span><a href="#Building-a-Training-Loop" data-toc-modified-id="Building-a-Training-Loop-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Building a Training Loop</a></span></li></ul></div>

In [218]:
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import pandas as pd

# embed static images in the ipynb
%matplotlib inline 

Q: Import PyTorch.

In [6]:
import torch
import numpy as np

Q: In Jupyter, print the version of PyTorch installed.

In [7]:
torch.__version__

'1.5.1'

In [8]:
def display_attributes(obj):
    """Prints the class attributes (str) of an object.

    Args:
        obj : Any object in Python
    """    
    attributes = ', '.join(i for i in dir(obj) if not i.startswith('_'))
    # source note: https://tinyurl.com/yyef5trl | stack overflow
    print(attributes+'\n')

TODO: 
- describe the "why"
- PyTorch vs. TensorFlow
- describe installation
- describe recommended pre-requisites

In [9]:
x = np.array(5)
x.ndim

0

Q: Print a tensor of dimension 0.

In [10]:
torch.tensor(5)

tensor(5)

In [11]:
torch.tensor(5).ndim?

Object `ndim` not found.


In [ ]:
torch.tensor(5).ndim

In [12]:
torch.Tensor.ndim?

Type:        getset_descriptor
String form: <attribute 'ndim' of 'torch._C._TensorBase' objects>
Docstring:   Alias for :meth:`~Tensor.dim()`


In [13]:
torch.tensor(5).ndim

0

Q: Print a tensor of dimension 1. 

In [14]:
torch.tensor([5])

tensor([5])

In [15]:
torch.tensor([5]).ndim

1

Q: What is the dimension of the following tensor? 
```python
torch.tensor([5, 5])
```
Also, return it. 

In [16]:
torch.tensor([5, 5]).ndim

1

Q: Print a tensor of dimension 2. 

In [17]:
torch.tensor([[5, 5],
              [5, 5]])

tensor([[5, 5],
        [5, 5]])

Q: 

In [18]:
x = torch.tensor([[1, 2],
                  [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

Q: Return the matrix dimensions of `x` using an attribute.

In [19]:
x = torch.tensor([[1, 2],
                  [3, 4]])

In [20]:
x.shape

torch.Size([2, 2])

Q: Return the shape of `x` by using a function, not an attribute.

In [21]:
x = torch.tensor([[1, 2],
                  [3, 4]])

In [22]:
x.size() # works like np.shape

torch.Size([2, 2])

In [23]:
x.shape

torch.Size([2, 2])

Q: Multiply `x` by 2 element-wise.

In [24]:
# element-wise multiplication by a scalar
x * 2

tensor([[2, 4],
        [6, 8]])

Q: Multiply `x` and `y` element-wise with an operator. 

In [25]:
x = torch.rand(2,2)
y = torch.rand(2,2)

# element-wise multiplication of tensors
x * y 

tensor([[0.2513, 0.1479],
        [0.0831, 0.0087]])

Q: Add `x` and `y` element-wise with an operator.

In [26]:
# element-wise addition of tensors
x + y 

tensor([[1.0045, 0.9407],
        [0.5766, 0.3435]])

Q: Add `x` and `y` element-wise with a function.

In [27]:
# Also element-wise addition of tensors
torch.add(x, y)

tensor([[1.0045, 0.9407],
        [0.5766, 0.3435]])

Q: Return a 1D tensor of zeros with length 4.

In [28]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

Q: Return a 2 by 3 zero matrix (as a tensor).

In [29]:
torch.zeros([2, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Q: What method lets you return a tensor filled with random numbers from a uniform distribution
on the interval $[0, 1)$?

`torch.rand`

Q: Return a tensor of shape (2, ) filled w/ random numbers $\sim\text{Uniform}(0,1)$.

In [30]:
torch.rand(2)

tensor([0.4301, 0.6362])

Q: Return a tensor of shape (2,2) filled w/ random numbers $\sim\text{Uniform}(0,1)$.

In [31]:
torch.rand([2,2])

tensor([[0.4524, 0.9985],
        [0.8980, 0.6122]])

Q: Return a 2 by 5 tensor, $y$, filled w/ random numbers $\sim\text{Uniform}(0,1)$.

In [32]:
y = torch.rand([2, 5])
y

tensor([[0.3044, 0.1350, 0.9358, 0.2429, 0.8446],
        [0.6894, 0.8933, 0.2210, 0.3393, 0.0139]])

In [33]:
torch.Tensor.view?

Docstring:
view(*shape) -> Tensor

Returns a new tensor with the same data as the :attr:`self` tensor but of a
different :attr:`shape`.

The returned tensor shares the same data and must have the same number
of elements, but may have a different size. For a tensor to be viewed, the new
view size must be compatible with its original size and stride, i.e., each new
view dimension must either be a subspace of an original dimension, or only span
across original dimensions :math:`d, d+1, \dots, d+k` that satisfy the following
contiguity-like condition that :math:`\forall i = 0, \dots, k-1`,

.. math::

  \text{stride}[i] = \text{stride}[i+1] \times \text{size}[i+1]

Otherwise, :meth:`contiguous` needs to be called before the tensor can be
viewed. See also: :meth:`reshape`, which returns a view if the shapes are
compatible, and copies (equivalent to calling :meth:`contiguous`) otherwise.

Args:
    shape (torch.Size or int...): the desired size

Example::

    >>> x = torch.randn(4, 4)
    >

In [34]:
y.view([5, 2]) # similar to ndarray.reshape

tensor([[0.3044, 0.1350],
        [0.9358, 0.2429],
        [0.8446, 0.6894],
        [0.8933, 0.2210],
        [0.3393, 0.0139]])

Q: 

In [35]:
torch.empty(5)

tensor([8.1919e-10, 6.4522e-07, 8.1723e+20, 1.7247e-07, 4.2111e-11])

Q: 

In [36]:
torch.empty(4,4)

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38, 9.6429e-39]])

Q: 

In [37]:
x

tensor([[0.5338, 0.7411],
        [0.2965, 0.0275]])

In [38]:
x[:, -1]

tensor([0.7411, 0.0275])

Q: 

In [39]:
x = torch.rand(4,4)
x, x[::2]

(tensor([[0.0708, 0.7817, 0.1098, 0.4757],
         [0.4302, 0.7755, 0.5509, 0.3893],
         [0.4159, 0.6323, 0.6677, 0.5191],
         [0.8978, 0.3408, 0.9920, 0.3433]]),
 tensor([[0.0708, 0.7817, 0.1098, 0.4757],
         [0.4159, 0.6323, 0.6677, 0.5191]]))

Q: 

In [40]:
x = torch.ones(5)
x

tensor([1., 1., 1., 1., 1.])

Q: 

In [41]:
x.add_(1)

tensor([2., 2., 2., 2., 2.])

Q: 

In [42]:
nd =  np.arange(5)
tenzin = torch.from_numpy(nd)

tenzin

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

Q: 

In [43]:
def display_attributes(obj):
    """Prints the class attributes (str) of an object.

    Args:
        obj : Any object in Python
    """    
    attributes = ', '.join(i for i in dir(obj) if not i.startswith('_'))
    # source note: https://tinyurl.com/yyef5trl | stack overflow
    print(attributes+'\n')

In [44]:
from torch.utils import data
display_attributes(data)

BatchSampler, ChainDataset, ConcatDataset, DataLoader, Dataset, DistributedSampler, IterableDataset, RandomSampler, Sampler, SequentialSampler, Subset, SubsetRandomSampler, TensorDataset, WeightedRandomSampler, dataloader, dataset, distributed, get_worker_info, random_split, sampler



In [45]:
from torch.utils.data import DataLoader
display_attributes(DataLoader)

multiprocessing_context



Q:

Q: Check if $x$ is a tensor.

In [46]:
x = [1, 2, 3]

In [47]:
torch.is_tensor(x)

False

Q: Check if $x$ is stored as a tensor.

Q: 

In [48]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [49]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

Q: 

In [50]:
torch.linspace(2, 10, steps=3)

tensor([ 2.,  6., 10.])

Q: 

In [51]:
torch.logspace(-1, 1, 4)

tensor([ 0.1000,  0.4642,  2.1544, 10.0000])

Q: 

Q: 

Q: 

In [52]:
# random permutation
torch.randperm(5)

tensor([4, 0, 3, 1, 2])

Q: 

In [53]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [54]:
torch.arange(5, 5)

tensor([], dtype=torch.int64)

In [55]:
torch.arange?

Docstring:
arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a 1-D tensor of size :math:`\left\lceil \frac{\text{end} - \text{start}}{\text{step}} \right\rceil`
with values from the interval ``[start, end)`` taken with common difference
:attr:`step` beginning from `start`.

Note that non-integer :attr:`step` is subject to floating point rounding errors when
comparing against :attr:`end`; to avoid inconsistency, we advise adding a small epsilon to :attr:`end`
in such cases.

.. math::
    \text{out}_{{i+1}} = \text{out}_{i} + \text{step}

Args:
    start (Number): the starting value for the set of points. Default: ``0``.
    end (Number): the ending value for the set of points
    step (Number): the gap between each pair of adjacent points. Default: ``1``.
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``Non

In [56]:
torch.arange(10, 20)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [57]:
torch.arange(10, 20, 2)

tensor([10, 12, 14, 16, 18])

Q: 

In [58]:
torch.randn(4, 5)

tensor([[-1.0217, -0.7316, -2.1996, -0.3324,  2.6727],
        [-0.1591, -0.4618, -0.3964, -2.6516, -0.2281],
        [ 0.8170,  0.1279, -2.3949,  1.2962, -1.0427],
        [-1.9214, -1.2680,  1.4160, -0.9041,  1.7445]])

Q: 

In [59]:
torch.randint?

Docstring:
randint(low=0, high, size, *, generator=None, out=None, \
        dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with random integers generated uniformly
between :attr:`low` (inclusive) and :attr:`high` (exclusive).

The shape of the tensor is defined by the variable argument :attr:`size`.

.. note:
    With the global dtype default (``torch.float32``), this function returns
    a tensor with dtype ``torch.int64``.

Args:
    low (int, optional): Lowest integer to be drawn from the distribution. Default: 0.
    high (int): One above the highest integer to be drawn from the distribution.
    size (tuple): a tuple defining the shape of the output tensor.
    generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a globa

Q: 

In [60]:
tenzin = torch.randint(high=5, size=(3,3))
tenzin

tensor([[4, 1, 1],
        [1, 1, 3],
        [0, 1, 4]])

Q: To returns the index of the minimum value of a tensor, use `torch.argmin`

Q: 

In [61]:
torch.argmin(tenzin, dim=1)

tensor([2, 1, 0])

Q: 

In [62]:
torch.argmin(tenzin, dim=0)

tensor([2, 2, 0])

Q: 

Q: 

Q: 

In [63]:
x, y = torch.rand(4), torch.rand(4)
x, y

(tensor([0.0568, 0.6620, 0.6469, 0.6562]),
 tensor([0.5470, 0.9248, 0.2639, 0.0231]))

In [64]:
torch.cat((x, y))

tensor([0.0568, 0.6620, 0.6469, 0.6562, 0.5470, 0.9248, 0.2639, 0.0231])

Q: 

In [65]:
x, y, z = torch.arange(3), torch.arange(3), torch.arange(3)
x, y, z

(tensor([0, 1, 2]), tensor([0, 1, 2]), tensor([0, 1, 2]))

In [66]:
torch.cat((x, y, z), dim=0) 

tensor([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [67]:
x = torch.eye(3)
y = 2*torch.eye(3)
x, y

(tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 tensor([[2., 0., 0.],
         [0., 2., 0.],
         [0., 0., 2.]]))

In [68]:
torch.cat((x, y), dim=0) 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [69]:
torch.cat((x, y), dim=1) 

tensor([[1., 0., 0., 2., 0., 0.],
        [0., 1., 0., 0., 2., 0.],
        [0., 0., 1., 0., 0., 2.]])

Q: 

Q: 

In [70]:
I = torch.eye(4)
torch.chunk(I, 2)

(tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.]]),
 tensor([[0., 0., 1., 0.],
         [0., 0., 0., 1.]]))

In [71]:
torch.chunk(I, 1)

(tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]),)

In [72]:
torch.chunk(I, 4)

(tensor([[1., 0., 0., 0.]]),
 tensor([[0., 1., 0., 0.]]),
 tensor([[0., 0., 1., 0.]]),
 tensor([[0., 0., 0., 1.]]))

In [73]:
torch.chunk(I, 3)

(tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.]]),
 tensor([[0., 0., 1., 0.],
         [0., 0., 0., 1.]]))

In [74]:
torch.chunk(I, 4)[:]

(tensor([[1., 0., 0., 0.]]),
 tensor([[0., 1., 0., 0.]]),
 tensor([[0., 0., 1., 0.]]),
 tensor([[0., 0., 0., 1.]]))

In [75]:
torch.chunk(input=I,chunks=2, dim=0)

(tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.]]),
 tensor([[0., 0., 1., 0.],
         [0., 0., 0., 1.]]))

In [76]:
torch.chunk(input=I,chunks=2, dim=1)

(tensor([[1., 0.],
         [0., 1.],
         [0., 0.],
         [0., 0.]]),
 tensor([[0., 0.],
         [0., 0.],
         [1., 0.],
         [0., 1.]]))

Q: 

In [77]:
x = np.arange(4).reshape(2,2)
torch.Tensor(x)

tensor([[0., 1.],
        [2., 3.]])

Q: 

Q: 

Q: 

In [78]:
x = np.eye(3)
torch.nonzero(torch.Tensor(x))

..\torch\csrc\utils\python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)


tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [79]:
x = torch.randint(4, (3,3))
x

tensor([[0, 0, 3],
        [1, 3, 0],
        [2, 2, 1]])

In [80]:
torch.nonzero(x)

tensor([[0, 2],
        [1, 0],
        [1, 1],
        [2, 0],
        [2, 1],
        [2, 2]])

Q: 

Q: 

In [81]:
x

tensor([[0, 0, 3],
        [1, 3, 0],
        [2, 2, 1]])

In [82]:
torch.split(x, 2)

(tensor([[0, 0, 3],
         [1, 3, 0]]),
 tensor([[2, 2, 1]]))

In [83]:
torch.split(x, 1)

(tensor([[0, 0, 3]]), tensor([[1, 3, 0]]), tensor([[2, 2, 1]]))

In [84]:
torch.split(x, 3)

(tensor([[0, 0, 3],
         [1, 3, 0],
         [2, 2, 1]]),)

Q: 

Q: 

Q: 

In [85]:
torch.randint?

Docstring:
randint(low=0, high, size, *, generator=None, out=None, \
        dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with random integers generated uniformly
between :attr:`low` (inclusive) and :attr:`high` (exclusive).

The shape of the tensor is defined by the variable argument :attr:`size`.

.. note:
    With the global dtype default (``torch.float32``), this function returns
    a tensor with dtype ``torch.int64``.

Args:
    low (int, optional): Lowest integer to be drawn from the distribution. Default: 0.
    high (int): One above the highest integer to be drawn from the distribution.
    size (tuple): a tuple defining the shape of the output tensor.
    generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a globa

Q: 

In [86]:
x = torch.eye(2)
type(x)

torch.Tensor

Q: 

In [87]:
# not in place
x = torch.ones(1)

x_i = x
x = x + 1

print(x, x_i)

tensor([2.]) tensor([1.])


In [88]:
# in place
x = torch.ones(1)

x_i = x
x += 1

print(x, x_i)

tensor([2.]) tensor([2.])


Q: 

In [89]:
x = torch.arange(1,7)
x

tensor([1, 2, 3, 4, 5, 6])

In [90]:
x.view(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [91]:
x.view(2, -1) # -1 makes torch infer the missing dimension.

tensor([[1, 2, 3],
        [4, 5, 6]])

Q: 

Q: 

torch.Tensor.view does not create a copy. 

Different views share the same data.

A function `reshape` exists, but it creates a copy of the Tensor

Q: 

In [92]:
torch.cuda.is_available() # Check if we cna use GPUs

False

Reference: GPU usage basics [Evann Courdier](https://youtu.be/pWrwyOsho5A?t=734)

Q: 

### Type Conversion

In [93]:
x = torch.rand((2,4))
Y = 4 * x
Y.dtype, Y

(torch.float32,
 tensor([[0.6994, 1.3480, 3.0409, 1.2484],
         [3.6850, 0.0273, 3.1673, 2.1888]]))

In [94]:
Y.to(torch.float16)

tensor([[0.6992, 1.3477, 3.0410, 1.2480],
        [3.6855, 0.0273, 3.1680, 2.1895]], dtype=torch.float16)

In [95]:
Y.to(torch.int64)

tensor([[0, 1, 3, 1],
        [3, 0, 3, 2]])

### `torch.Tensor` can switch to and from the `np.ndarray`

In [97]:
x = np.random.randint(low=0, 
                      high=5, 
                      size=(2,2))
x

array([[1, 0],
       [4, 1]])

In [98]:
y = torch.from_numpy(x)
y

tensor([[1, 0],
        [4, 1]], dtype=torch.int32)

In [99]:
x = y.numpy()
x

array([[1, 0],
       [4, 1]])

----

## Building a Training Loop

continue from [video](https://youtu.be/pWrwyOsho5A?t=995)

Q: 

Q: 