In [84]:
import torch
import numpy as np

TODO: 
- describe the "why"
- PyTorch vs. TensorFlow
- describe installation
- describe recommended pre-requisites

Q: 

In [85]:
torch.tensor(5)

tensor(5)

Q: 

In [86]:
torch.tensor([5])

tensor([5])

Q: 

In [87]:
torch.tensor([5, 5])

tensor([5, 5])

Q: 

In [88]:
torch.tensor([[5, 5],
              [5, 5]])

tensor([[5, 5],
        [5, 5]])

Q: 

In [89]:
x = torch.tensor([[1, 2], [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

Q: 

In [90]:
x.size() # works like np.shape
# Notice this is a function, not an attribue

torch.Size([2, 2])

Q: 

In [91]:
# element-wise multiplication by a scalar
y = x * 2
y

tensor([[2, 4],
        [6, 8]])

Q: 

In [92]:
x = torch.rand(2,2)
y = torch.rand(2,2)

# element-wise multiplication of tensors
x * y 

tensor([[5.8915e-01, 1.7541e-01],
        [1.1933e-04, 6.5765e-01]])

Q: 

In [93]:
# element-wise addition of tensors
x + y 

tensor([[1.5782, 0.9006],
        [0.1570, 1.6268]])

Q: 

In [94]:
# Also element-wise addition of tensors
torch.add(x, y)

tensor([[1.5782, 0.9006],
        [0.1570, 1.6268]])

Q: 

In [95]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

Q: 

In [96]:
torch.zeros([2, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Q: 

In [97]:
torch.rand(2)

tensor([0.4877, 0.4502])

Q: 

In [98]:
torch.rand([2,2])

tensor([[0.6212, 0.8982],
        [0.2418, 0.4845]])

Q: 

In [99]:
y = torch.rand([2, 5])

In [100]:
y.view([5, 2]) # equivalent of ndarray.reshape

tensor([[0.5221, 0.3011],
        [0.8465, 0.7131],
        [0.6657, 0.4171],
        [0.4768, 0.7649],
        [0.1988, 0.0649]])

In [101]:
y

tensor([[0.5221, 0.3011, 0.8465, 0.7131, 0.6657],
        [0.4171, 0.4768, 0.7649, 0.1988, 0.0649]])

Q: 

In [102]:
torch.empty(5)

tensor([0.0000e+00, 0.0000e+00, 1.4013e-44, 0.0000e+00, 1.4013e-45])

Q: 

In [103]:
torch.empty(4,4)

tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 9.7346e-39, 1.0745e-38, 1.0102e-38]])

Q: 

In [104]:
x

tensor([[0.6060, 0.6157],
        [0.1563, 0.7502]])

In [105]:
x[:, -1]

tensor([0.6157, 0.7502])

Q: 

In [106]:
x = torch.rand(4,4)
x, x[::2]

(tensor([[0.5151, 0.1323, 0.7956, 0.9001],
         [0.4779, 0.3232, 0.4146, 0.2782],
         [0.8317, 0.4717, 0.5555, 0.7215],
         [0.3922, 0.8680, 0.6891, 0.9429]]),
 tensor([[0.5151, 0.1323, 0.7956, 0.9001],
         [0.8317, 0.4717, 0.5555, 0.7215]]))

Q: 

In [107]:
x = torch.ones(5)
x

tensor([1., 1., 1., 1., 1.])

Q: 

In [108]:
x.add_(1)

tensor([2., 2., 2., 2., 2.])

Q: 

In [109]:
nd =  np.arange(5)
tenzin = torch.from_numpy(nd)

tenzin

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

Q: 

In [110]:
from torchvision.datasets import MNIST

```python
MNIST('/data') # This will give you the following error
``` 
```
RuntimeError: Dataset not found. You can use download=True to download it
```

In [111]:
dir(MNIST)

['__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_exists',
 '_format_transform_repr',
 '_repr_indent',
 'class_to_idx',
 'classes',
 'download',
 'extra_repr',
 'processed_folder',
 'raw_folder',
 'resources',
 'test_data',
 'test_file',
 'test_labels',
 'train_data',
 'train_labels',
 'training_file']

In [112]:
MNIST('./', download=True)

Dataset MNIST
    Number of datapoints: 60000
    Root location: ./
    Split: Train

This placed a folder called MNIST inside the directory of the notebook.

In [113]:
from torch.utils.data import DataLoader